apiVersion: apps/v1
kind: Deployment
metadata:
  name: nerf-deployment
  labels:
    app: nerf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nerf
  template:
    metadata:
      name: nerf-pods
      #annotations:
        #tf-version.cloud-tpus.google.com: "2.7.0"
      labels:
        app: nerf
    spec:
      containers:
      - name: nerf
        image: gcr.io/spe3d-331118/flaskjaxnerf
        command: ["/bin/bash", "-c"]
        args:
        - >
          ls &&
          echo $KUBE_GOOGLE_CLOUD_TPU_ENDPOINTS &&
          export TPU_MESH_CONTROLLER_ADDRESS=(${KUBE_GOOGLE_CLOUD_TPU_ENDPOINTS//:/}) &&
          export TPU_MESH_CONTROLLER_ADDRESS=(${TPU_MESH_CONTROLLER_ADDRESS//grpc\/\//}) &&
          export TPU_MESH_CONTROLLER_ADDRESS=(${TPU_MESH_CONTROLLER_ADDRESS//8470/}) &&
          export TPU_MESH_CONTROLLER_ADDRESS=${TPU_MESH_CONTROLLER_ADDRESS[0]}:8476 &&
          export COLAB_TPU_ADDR=(${KUBE_GOOGLE_CLOUD_TPU_ENDPOINTS//grpc:\/\//}) &&
          echo $TPU_MESH_CONTROLLER_ADDRESS &&
          python -m jaxnerf.app
        #resources:
          #limits:
            #cloud-tpus.google.com/v2: 8
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: nerf
spec:
  type: NodePort
  selector:
    app: nerf
  ports:
  - name: nerf
    port: 3000
    targetPort: 3000
    nodePort: 30000